PULP_APP = demo-03-app
PULP_APP_FC_SRCS = demo-03.c ../common/tag_bits.c ../common/policy.c
PULP_APP_HOST_SRCS = demo-03.c ../common/tag_bits.c ../common/policy.c
PULP_CFLAGS = -O0 -ggdb3
PULP_LDFLAGS = -ggdb3

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
