PULP_APP = prop-test-app
#PULP_APP_FC_SRCS = prop-test.c
#PULP_APP_HOST_SRCS = prop-test.c
PULP_APP_FC_ASM_SRCS = prop-test.S prop-test-store.S prop-test-load.S prop-test-alu.S
#PULP_APP_HOST_ASM_SRCS =
PULP_CFLAGS = -O3 -g

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
