PULP_APP = demo-01-app
PULP_APP_FC_SRCS = demo-01.c ../common/tag_bits.c ../common/policy.c
PULP_APP_HOST_SRCS = demo-01.c ../common/tag_bits.c ../common/policy.c
PULP_CFLAGS = -O0 -g

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
